# Generated by Django 5.2.7 on 2025-11-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "name_uz",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["region", "name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "name_uz",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("body", models.TextField(blank=True, null=True, verbose_name="Body")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="additional_info/",
                        verbose_name="File",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "bot_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to="accounts.botuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Info",
                "verbose_name_plural": "Additional Info",
                "ordering": ["-created_at"],
            },
        ),
    ]
