# Generated by Django 5.2.7 on 2025-12-05 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_add_audit_log"),
        ("organizations", "0010_branch_show_pricelist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("receipt_pending", "Receipt Pending Verification"),
                            ("order_new", "New Order"),
                            ("order_cancelled", "Order Cancelled"),
                            ("user_new", "New User"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to="organizations.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to="organizations.translationcenter",
                        verbose_name="Translation Center",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Read By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Notification",
                "verbose_name_plural": "Admin Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "created_at"],
                        name="core_adminn_is_read_11f2db_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="core_adminn_notific_8a5f17_idx",
                    ),
                    models.Index(
                        fields=["branch", "is_read"],
                        name="core_adminn_branch__3a2e8a_idx",
                    ),
                    models.Index(
                        fields=["center", "is_read"],
                        name="core_adminn_center__8448c6_idx",
                    ),
                ],
            },
        ),
    ]
