# Generated by Django 5.2.7 on 2025-12-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_admin_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("receipt_pending", "Receipt Pending Verification"),
                    ("order_new", "New Order"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_completed", "Order Completed"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("user_new", "New User Registered"),
                    ("agency_new", "New Agency Registered"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
