# Generated by Django 5.2.7 on 2026-03-13 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_adminnotification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Read At')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='core.adminnotification', verbose_name='Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Read',
                'verbose_name_plural': 'Notification Reads',
                'indexes': [models.Index(fields=['user'], name='core_notifi_user_id_e52beb_idx'), models.Index(fields=['notification', 'user'], name='core_notifi_notific_beab4a_idx')],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
