# Generated by Django 5.2.7 on 2025-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["name"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="can_assign_orders",
            field=models.BooleanField(default=False, verbose_name="Can assign orders"),
        ),
        migrations.AddField(
            model_name="role",
            name="can_export_data",
            field=models.BooleanField(default=False, verbose_name="Can export data"),
        ),
        migrations.AddField(
            model_name="role",
            name="can_manage_customers",
            field=models.BooleanField(
                default=False, verbose_name="Can manage customers"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Display Name"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(
                default=False,
                help_text="System roles cannot be deleted",
                verbose_name="System Role",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
    ]
