# Generated by Django 5.2.7 on 2025-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_branch_show_pricelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_create_agencies",
            field=models.BooleanField(
                default=False,
                help_text="Can create new agency profiles and generate invite links",
                verbose_name="Can create agencies",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_delete_agencies",
            field=models.BooleanField(
                default=False,
                help_text="Can delete agency profiles",
                verbose_name="Can delete agencies",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_edit_agencies",
            field=models.BooleanField(
                default=False,
                help_text="Can edit agency details and reset invite links",
                verbose_name="Can edit agencies",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_manage_agencies",
            field=models.BooleanField(
                default=False,
                help_text="Full agency management - overrides other agency permissions",
                verbose_name="Can manage agencies (full access)",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_agencies",
            field=models.BooleanField(
                default=False,
                help_text="Can view list of agency partners",
                verbose_name="Can view agencies",
            ),
        ),
    ]
