# Generated by Django 5.2.7 on 2025-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_add_agency_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationcenter",
            name="subdomain",
            field=models.SlugField(
                blank=True,
                help_text="Unique subdomain for this center (e.g., 'center1' for center1.alltranslation.uz)",
                max_length=63,
                null=True,
                unique=True,
                verbose_name="Subdomain",
            ),
        ),
    ]
