# Generated by Django 5.2.7 on 2025-12-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_add_subdomain_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_manage_center',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_customer_details',
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_branches',
            field=models.BooleanField(default=False, help_text='Can create new branches', verbose_name='Can create branches'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_centers',
            field=models.BooleanField(default=False, help_text='Can create new translation centers', verbose_name='Can create centers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_products',
            field=models.BooleanField(default=False, verbose_name='Can create products'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_staff',
            field=models.BooleanField(default=False, help_text='Can create new staff members', verbose_name='Can create staff'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_branches',
            field=models.BooleanField(default=False, help_text='Can delete branches', verbose_name='Can delete branches'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_centers',
            field=models.BooleanField(default=False, help_text='Can delete translation centers', verbose_name='Can delete centers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_customers',
            field=models.BooleanField(default=False, verbose_name='Can delete customers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_products',
            field=models.BooleanField(default=False, verbose_name='Can delete products'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_staff',
            field=models.BooleanField(default=False, help_text='Can delete staff members', verbose_name='Can delete staff'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_branches',
            field=models.BooleanField(default=False, help_text='Can edit branch settings', verbose_name='Can edit branches'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_centers',
            field=models.BooleanField(default=False, help_text='Can edit translation center settings', verbose_name='Can edit centers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_customers',
            field=models.BooleanField(default=False, verbose_name='Can edit customers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_products',
            field=models.BooleanField(default=False, verbose_name='Can edit products'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_staff',
            field=models.BooleanField(default=False, help_text='Can edit staff details and roles', verbose_name='Can edit staff'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_centers',
            field=models.BooleanField(default=False, help_text='Full center management - overrides other center permissions', verbose_name='Can manage centers (full access)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_financial',
            field=models.BooleanField(default=False, help_text='Full financial management - overrides other financial permissions', verbose_name='Can manage financial (full access)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_marketing',
            field=models.BooleanField(default=False, help_text='Full marketing management - overrides other marketing permissions', verbose_name='Can manage marketing (full access)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_reports',
            field=models.BooleanField(default=False, help_text='Full reports management - overrides other report permissions', verbose_name='Can manage reports (full access)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_branches',
            field=models.BooleanField(default=False, help_text='Can view branch details', verbose_name='Can view branches'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_centers',
            field=models.BooleanField(default=False, help_text='Can view translation center details', verbose_name='Can view centers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_customers',
            field=models.BooleanField(default=False, verbose_name='Can view customers'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_products',
            field=models.BooleanField(default=False, verbose_name='Can view products'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_branches',
            field=models.BooleanField(default=False, help_text='Full branch management - overrides other branch permissions', verbose_name='Can manage branches (full access)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_customers',
            field=models.BooleanField(default=False, help_text='Full customer management - overrides other customer permissions', verbose_name='Can manage customers (full access)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Full product management - overrides other product permissions', verbose_name='Can manage products (full access)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_staff',
            field=models.BooleanField(default=False, help_text='Full staff management - overrides other staff permissions', verbose_name='Can manage staff (full access)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_view_staff',
            field=models.BooleanField(default=False, help_text='Can view staff details', verbose_name='Can view staff'),
        ),
    ]
