# Generated by Django 5.2.7 on 2025-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_split_granular_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_view_audit_logs",
            field=models.BooleanField(
                default=False,
                help_text="Can view system audit logs and activity history",
                verbose_name="Can view audit logs",
            ),
        ),
    ]
