# Generated by Django 5.2.7 on 2025-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_add_audit_log_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_export_audit_logs",
            field=models.BooleanField(
                default=False,
                help_text="Can export audit log data to CSV/Excel",
                verbose_name="Can export audit logs",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_grant_audit_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Can assign audit log permissions to lower-level users",
                verbose_name="Can grant audit permissions",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_manage_audit_logs",
            field=models.BooleanField(
                default=False,
                help_text="Full audit log access - overrides other audit log permissions",
                verbose_name="Can manage audit logs (full access)",
            ),
        ),
    ]
