# Generated by Django 5.2.7 on 2025-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_add_bot_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_create_customers",
            field=models.BooleanField(
                default=False,
                help_text="Can create new customer profiles",
                verbose_name="Can create customers",
            ),
        ),
    ]
