# Generated by Django 5.2.7 on 2025-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_role_can_create_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_expenses',
            field=models.BooleanField(default=False, verbose_name='Can create expenses'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_expenses',
            field=models.BooleanField(default=False, verbose_name='Can delete expenses'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_expenses',
            field=models.BooleanField(default=False, verbose_name='Can edit expenses'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_expenses',
            field=models.BooleanField(default=False, help_text='Full expense management - overrides other expense permissions', verbose_name='Can manage expenses (full access)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_expenses',
            field=models.BooleanField(default=False, verbose_name='Can view expenses'),
        ),
    ]
