# Generated by Django 5.2.7 on 2026-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_role_can_assign_bulk_payment_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_languages',
            field=models.BooleanField(default=False, verbose_name='Can create languages'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_languages',
            field=models.BooleanField(default=False, verbose_name='Can edit languages'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_languages',
            field=models.BooleanField(default=False, help_text='Full language management - overrides other language permissions', verbose_name='Can manage languages (full access)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_languages',
            field=models.BooleanField(default=False, verbose_name='Can view languages'),
        ),
    ]
