# Generated by Django 5.2.7 on 2026-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_alter_translationcenter_company_orders_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_delete_languages',
            field=models.BooleanField(default=False, verbose_name='Can delete languages'),
        ),
    ]
