# Generated by Django 5.2.7 on 2026-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_role_can_delete_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_edit_price',
            field=models.BooleanField(default=False, verbose_name='Can edit order price'),
        ),
    ]
