# Generated by Django 5.2.7 on 2026-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_rename_marketing_b_post_id_8f6c3e_idx_marketing_b_post_id_95de66_idx_and_more'),
        ('organizations', '0022_role_can_delete_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpost',
            name='target_branches',
            field=models.ManyToManyField(blank=True, help_text='Multiple branches for multi-branch broadcasts', related_name='multi_marketing_posts', to='organizations.branch', verbose_name='Target Branches'),
        ),
        migrations.AddField(
            model_name='marketingpost',
            name='target_centers',
            field=models.ManyToManyField(blank=True, help_text='Multiple centers for multi-center broadcasts', related_name='multi_marketing_posts', to='organizations.translationcenter', verbose_name='Target Centers'),
        ),
    ]
