# Generated by Django 5.2.7 on 2025-11-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Language Name"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Short Name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Service Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "charging",
                    models.CharField(
                        choices=[
                            ("static", "Bir xil narx"),
                            ("dynamic", "Page soniga qarab narx"),
                        ],
                        max_length=20,
                        verbose_name="Charging Type",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        to="services.language", verbose_name="Languages"
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Service",
                "verbose_name_plural": "Main Services",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Document Type"),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Document Type"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Document Type"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Document Type"
                    ),
                ),
                (
                    "ordinary_first_page_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="First Page Price for Regular Users",
                    ),
                ),
                (
                    "ordinary_other_page_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Other Pages Price for Regular Users",
                    ),
                ),
                (
                    "agency_first_page_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="First Page Price for Agencies",
                    ),
                ),
                (
                    "agency_other_page_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Other Pages Price for Agencies",
                    ),
                ),
                (
                    "agency_copy_price_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Percentage of total price for a copy of the document for agency",
                        max_digits=5,
                    ),
                ),
                (
                    "user_copy_price_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Percentage of total price for a copy of the document for user",
                        max_digits=5,
                    ),
                ),
                (
                    "min_pages",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Minimum Pages"
                    ),
                ),
                (
                    "estimated_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Estimated Days"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.category",
                        verbose_name="Main Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "unique_together": {("category", "name")},
            },
        ),
    ]
