# Generated by Django 5.2.7 on 2025-11-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_role_options_role_can_assign_orders_and_more"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="branch",
            field=models.ForeignKey(
                default=1,
                help_text="Branch this category belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="organizations.branch",
                verbose_name="Branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Service Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Service Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Service Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Service Name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("branch", "name")},
        ),
    ]
