# Generated by Django 5.2.7 on 2026-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_split_expense_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='agency_copy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price per copy for agencies', max_digits=10, verbose_name='Agency Copy Price'),
        ),
        migrations.AddField(
            model_name='language',
            name='agency_other_page_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price per other page for agencies', max_digits=10, verbose_name='Agency Other Pages Price'),
        ),
        migrations.AddField(
            model_name='language',
            name='agency_page_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price for first page translation for agencies', max_digits=10, verbose_name='Agency First Page Price'),
        ),
        migrations.AddField(
            model_name='language',
            name='ordinary_copy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price per copy for ordinary users', max_digits=10, verbose_name='Ordinary User Copy Price'),
        ),
        migrations.AddField(
            model_name='language',
            name='ordinary_other_page_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price per other page for ordinary users', max_digits=10, verbose_name='Ordinary User Other Pages Price'),
        ),
        migrations.AddField(
            model_name='language',
            name='ordinary_page_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price for first page translation for ordinary users', max_digits=10, verbose_name='Ordinary User First Page Price'),
        ),
    ]
