# Generated by Django 5.2.7 on 2026-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_language_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Language Name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Language Name'),
        ),
    ]
