# Generated by Django 5.2.7 on 2026-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_product_written_verification_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='written_verification_required',
        ),
        migrations.AddField(
            model_name='category',
            name='written_verification_required',
            field=models.BooleanField(default=False, help_text='If enabled, the bot will ask users to type full names from their documents to avoid misspelling handwritten names.', verbose_name='Written Verification Required'),
        ),
    ]
