# Generated by Django 5.2.7 on 2026-03-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_role_can_delete_languages'),
        ('services', '0012_remove_product_written_verification_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('icon', models.CharField(blank=True, default='', help_text='e.g. mdi:office-building — leave blank for default', max_length=60, verbose_name='Iconify Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_expense_categories', to='organizations.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'General Expense Category',
                'verbose_name_plural': 'General Expense Categories',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount (UZS)')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='general_expense_receipts/', verbose_name='Receipt / Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_expenses', to='organizations.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_expenses', to='services.generalexpensecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'General Expense',
                'verbose_name_plural': 'General Expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='services_ge_branch__90c6d9_idx'), models.Index(fields=['category', 'date'], name='services_ge_categor_80e50c_idx')],
            },
        ),
    ]
