# Generated by Django 5.2.7 on 2026-03-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_translationcenter_payme_secret_key_prod'),
        ('services', '0014_generalexpense_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this language belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='organizations.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Language Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Short Name'),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('branch', 'name'), ('branch', 'short_name')},
        ),
    ]
