# Generated by Django 5.2.7 on 2025-11-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_card', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Bank Card')),
                ('holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Holder Name')),
                ('phone_number', models.PositiveBigIntegerField(default=0, verbose_name='Phone Number')),
                ('location', models.URLField(blank=True, null=True, verbose_name='Office location')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='Help Text')),
                ('help_text_uz', models.TextField(blank=True, null=True, verbose_name='Help Text')),
                ('help_text_ru', models.TextField(blank=True, null=True, verbose_name='Help Text')),
                ('help_text_en', models.TextField(blank=True, null=True, verbose_name='Help Text')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_uz', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_ru', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('about_us_en', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Additional Info',
                'verbose_name_plural': 'Additional Info',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=100, verbose_name='Language')),
                ('step', models.IntegerField(default=0, verbose_name='Registration Step')),
                ('agency_token', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Agency Token')),
                ('agency_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agency Link')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this invitation link has been used', verbose_name='Is Used')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_agency', models.BooleanField(default=False, verbose_name='Is Agency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_users', to='accounts.botuser', verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
