# Generated by Django 5.2.7 on 2025-12-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_guide_and_reserved_fields"),
        ("orders", "0004_add_receipt_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUserState",
            fields=[
                (
                    "bot_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="state",
                        serialize=False,
                        to="accounts.botuser",
                        verbose_name="Bot User",
                    ),
                ),
                (
                    "selected_category_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "selected_product_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "selected_language_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("copy_number", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_file_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of OrderMedia IDs for files uploaded in current session",
                        verbose_name="Uploaded File IDs",
                    ),
                ),
                ("total_pages", models.PositiveIntegerField(default=0)),
                (
                    "message_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of message IDs to clean up",
                        verbose_name="Message IDs",
                    ),
                ),
                ("totals_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "last_instruction_message_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "pending_payment_order_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "pending_receipt_order_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional temporary data during flows",
                        verbose_name="Extra Data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_states",
                        to="orders.order",
                        verbose_name="Current Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot User State",
                "verbose_name_plural": "Bot User States",
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="accounts_bo_updated_2c39a4_idx"
                    )
                ],
            },
        ),
    ]
