# Generated by Django 5.2.7 on 2025-11-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_media/', verbose_name='File')),
                ('pages', models.PositiveIntegerField(default=1, verbose_name='Pages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Order file',
                'verbose_name_plural': 'Order media',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.PositiveIntegerField(default=1, verbose_name='Total Pages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('payment_confirmed', 'Payment Confirmed'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=100, verbose_name='Payment Type')),
                ('recipt', models.FileField(blank=True, null=True, upload_to='recipts/', verbose_name='Receipt')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('copy_number', models.PositiveIntegerField(default=0, help_text='Additional copies needed (0 means only original)', verbose_name='Number of Copies')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.botuser', verbose_name='Telegram User')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.language', verbose_name='Language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.product', verbose_name='Document Type')),
                ('files', models.ManyToManyField(to='orders.ordermedia', verbose_name='Files')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
