# Generated by Django 5.2.7 on 2025-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_receipt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipt',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='recipts/', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, help_text='Receipt image or document', max_length=255, null=True, upload_to='receipts/%Y/%m/', verbose_name='Receipt File'),
        ),
    ]
