# Generated by Django 5.2.7 on 2025-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedia',
            name='file',
            field=models.FileField(max_length=255, upload_to='order_media/', verbose_name='File'),
        ),
    ]
