# Generated by Django 5.2.7 on 2025-12-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ordermedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedia',
            name='file',
            field=models.FileField(max_length=500, upload_to='order_media/', verbose_name='File'),
        ),
    ]
