# Generated by Django 5.2.7 on 2026-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_archived_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermedia',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='Telegram file ID for quick file access without downloading', max_length=200, null=True, verbose_name='Telegram File ID'),
        ),
    ]
