# Generated by Django 5.2.7 on 2026-03-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderpricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_files',
            field=models.ManyToManyField(blank=True, help_text='Supplementary documents provided alongside the main order files', related_name='additional_for_orders', to='orders.ordermedia', verbose_name='Additional Supply Documents'),
        ),
    ]
