# Generated by Django 5.2.7 on 2026-03-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_paymetransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='orders_paym_payme_t_aa3ff7_idx',
            old_name='orders_paym_payme_tr_7e8f90_idx',
        ),
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='orders_paym_state_b02488_idx',
            old_name='orders_paym_state_aa5929_idx',
        ),
        migrations.RenameIndex(
            model_name='paymetransaction',
            new_name='orders_paym_created_0d8997_idx',
            old_name='orders_paym_created__15244a_idx',
        ),
    ]
