# Generated by Django 5.2.7 on 2026-03-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_rename_orders_paym_payme_tr_7e8f90_idx_orders_paym_payme_t_aa3ff7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('payme', 'Payme')], db_index=True, default='manual', max_length=20, verbose_name='Payment Source'),
        ),
    ]
